"""
Agent Harness — simulates the multi-agent workflow.

For the PoC, subagent responses are simulated (hardcoded to match
the validation testcase). In production, these would be real LLM calls.

See docs/design/communication-protocol.md
"""

from __future__ import annotations
import tiktoken
from dataclasses import dataclass, field
from typing import Any
from src.dsl_parser import DslNode, parse_dsl
from src.dsl_serializer import serialize_dsl
from src.translator import dsl_to_nl, aggregate_results
from src.process_loader import ProcessDefinition, CompositionStep


@dataclass
class Message:
    msg_id: str
    from_agent: str
    to_agent: str
    wire_form: str
    parsed: DslNode | None = None


@dataclass
class TaskState:
    task_id: str
    agent_id: str
    status: str = "created"  # created, dispatched, in_progress, complete, failed
    retries: int = 0
    result: str = ""  # DSL wire form


@dataclass
class RunResult:
    """Result of running a process."""
    nl_output: str
    messages: list[Message] = field(default_factory=list)
    task_states: dict[str, TaskState] = field(default_factory=dict)
    token_counts: dict[str, int] = field(default_factory=dict)

    @property
    def dsl_token_count(self) -> int:
        return sum(
            self.token_counts.get(m.msg_id, 0)
            for m in self.messages
            if m.msg_id != "M7"
        )

    @property
    def nl_token_count(self) -> int:
        return self.token_counts.get("M7", 0)

    @property
    def total_tokens(self) -> int:
        return self.dsl_token_count + self.nl_token_count


# ── Simulated Subagent Responses ──

# These are the exact DSL messages from the validation testcase.
# In production, these would be generated by real LLM subagents.

SIMULATED_RESPONSES: dict[str, str] = {
    "t1": (
        '[result id=t1 status=complete]'
        '[artifact action=created lines=18 path=src/validation/user_schema.py type=file]'
        '[artifact action=modified lines="+23" path=src/handlers/user.py type=file]'
        '[added fn=validate_user_input in:RequestBody out:ValidationResult]'
        '[complexity delta="+2cyclomatic"]'
        '[/result]'
    ),
    "t2": (
        '[result id=t2 status=complete]'
        '[finding path=src/handlers/user.py:34 severity=minor]'
        'Email regex does not support international domains. '
        'Consider using a library like email-validator.'
        '[/finding]'
        '[security-check status=pass]'
        '[note]SQL injection not applicable — uses ORM[/note]'
        '[/security-check]'
        '[style status=pass]'
        '[verdict approve]'
        '[/result]'
    ),
    "t3": (
        '[result id=t3 status=complete]'
        '[artifact action=created lines=45 path=tests/test_user_validation.py type=file]'
        '[test-suite fail=1 pass=7 total=8]'
        '[test name=test_age_boundary_0 status=pass]'
        '[test name=test_age_boundary_150 status=pass]'
        '[test name=test_age_boundary_neg1 status=pass]'
        '[test name=test_age_200 status=pass]'
        '[test name=test_invalid_email status=pass]'
        '[test name=test_missing_name status=pass]'
        '[test name=test_valid_full_input status=pass]'
        '[test name=test_sql_injection_name reason="Input not sanitized — SQL chars pass through" status=fail]'
        '[/test-suite]'
        '[/result]'
    ),
}


def _count_tokens(text: str, encoding_name: str = "cl100k_base") -> int:
    """Count tokens using tiktoken."""
    enc = tiktoken.get_encoding(encoding_name)
    return len(enc.encode(text))


def _build_coder_task() -> str:
    """Build the M1 task message (Main -> Coder)."""
    return (
        '[task id=t1 type=code]'
        '[goal]Add input validation to POST /users endpoint[/goal]'
        '[file read=src/handlers/user.py]'
        '[spec]'
        '[field name=email required=true rule=format:email]'
        '[field name=name required=true rule=length:max=100]'
        '[field name=age required=false type=int rule=range:0-150]'
        '[on-invalid format=standard-error status=422]'
        '[/spec]'
        '[output-artifact path=src/handlers/user.py]'
        '[output-artifact path=src/validation/user_schema.py]'
        '[/task]'
    )


def _build_reviewer_task() -> str:
    """Build the M2 task message (Main -> Reviewer)."""
    return (
        '[task id=t2 type=review]'
        '[goal]Review validation code for correctness, security, style[/goal]'
        '[context-ref id=t1.artifacts]'
        '[focus correctness=true security=true style=true]'
        '[/task]'
    )


def _build_tester_task() -> str:
    """Build the M3 task message (Main -> Tester)."""
    return (
        '[task id=t3 type=test]'
        '[goal]Write and run tests for user input validation[/goal]'
        '[context-ref id=t1.artifacts]'
        '[test-cases]'
        '[case]valid email + name + age -> 200[/case]'
        '[case]invalid email -> 422[/case]'
        '[case]missing name -> 422[/case]'
        '[case]age 200 -> 422[/case]'
        '[/test-cases]'
        '[output-artifact path=tests/test_user_validation.py]'
        '[/task]'
    )


def run_process(process: ProcessDefinition, user_input: str) -> RunResult:
    """Run a process end-to-end.

    Simulates the full multi-agent workflow:
    1. Main agent decomposes user input into tasks
    2. Dispatches tasks to subagents
    3. Collects results
    4. Aggregates and produces NL output

    Args:
        process: Loaded process definition
        user_input: Natural language input from user

    Returns:
        RunResult with NL output, messages, and token counts
    """
    result = RunResult(nl_output="")
    msg_counter = 0

    def next_msg_id() -> str:
        nonlocal msg_counter
        msg_counter += 1
        return f"M{msg_counter}"

    def record_msg(from_agent: str, to_agent: str, wire_form: str) -> Message:
        msg_id = next_msg_id()
        tokens = _count_tokens(wire_form)
        msg = Message(
            msg_id=msg_id,
            from_agent=from_agent,
            to_agent=to_agent,
            wire_form=wire_form,
            parsed=parse_dsl(wire_form),
        )
        result.messages.append(msg)
        result.token_counts[msg_id] = tokens
        return msg

    # ── Step 1: Main agent decomposes user input ──
    # (In production, this is an LLM call. For PoC, we use hardcoded tasks.)

    # ── Step 2: Dispatch to Coder (M1) ──
    coder_task = _build_coder_task()
    record_msg("main", "coder", coder_task)

    # ── Step 3: Coder produces result (M4) ──
    coder_result = SIMULATED_RESPONSES["t1"]
    record_msg("coder", "main", coder_result)

    # ── Step 4: Dispatch to Reviewer (M2) and Tester (M3) ──
    # Both reference t1's artifacts via context-ref
    reviewer_task = _build_reviewer_task()
    record_msg("main", "reviewer", reviewer_task)

    tester_task = _build_tester_task()
    record_msg("main", "tester", tester_task)

    # ── Step 5: Collect results (M5, M6) ──
    reviewer_result = SIMULATED_RESPONSES["t2"]
    record_msg("reviewer", "main", reviewer_result)

    tester_result = SIMULATED_RESPONSES["t3"]
    record_msg("tester", "main", tester_result)

    # ── Step 6: Aggregate results → NL (M7) ──
    coder_nl = dsl_to_nl(coder_result, "coder")
    reviewer_nl = dsl_to_nl(reviewer_result, "reviewer")
    tester_nl = dsl_to_nl(tester_result, "tester")

    aggregated = aggregate_results({
        "coder": coder_nl,
        "reviewer": reviewer_nl,
        "tester": tester_nl,
    })

    # Record M7 (NL output — token counted separately)
    m7_id = next_msg_id()
    result.nl_output = aggregated
    result.token_counts[m7_id] = _count_tokens(aggregated)
    result.messages.append(Message(
        msg_id=m7_id,
        from_agent="main",
        to_agent="user",
        wire_form=aggregated,
    ))

    return result


def run_process_from_file(process_path: str, user_input: str) -> RunResult:
    """Convenience: load process from file and run."""
    from src.process_loader import load_process
    proc = load_process(process_path)
    return run_process(proc, user_input)
